
# Schema definitions for Liquicomun PRDV files
# Derived from user request

LIQUICOMUN_SCHEMA = {
    'liq_prdvbaqh': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'precio_eur_mwh': 'NUMERIC(18,3)',
        'periodo': 'INTEGER',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    },
    'liq_prdvdatos': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'periodo': 'INTEGER',
        'frr_subir_mwh': 'NUMERIC(18,3)',
        'frr_bajar_mwh': 'NUMERIC(18,3)',
        'rr_subir_mwh': 'NUMERIC(18,3)',
        'rr_bajar_mwh': 'NUMERIC(18,3)',
        'desvio_sistema_mwh': 'NUMERIC(18,3)',
        'pbalsub_euros_mwh': 'NUMERIC(18,3)',
        'pbalbaj_euros_mwh': 'NUMERIC(18,3)',
        'perc_frr_min_s_frr_may': 'NUMERIC(18,3)', # Normalized from % FRR MINORITARIA S/FRR MAYORITARIA
        'precio_unico_dual': 'TEXT', # Normalized from PRECIO  NICO/DUAL
        'precio_dual_desv_subir_euros_mwh': 'NUMERIC(18,3)',
        'precio_dual_desv_bajar_euros_mwh': 'NUMERIC(18,3)',
        'precio_unico_desv_euros_mwh': 'NUMERIC(18,3)',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    },
    'liq_prdvsuqh': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'precio_eur_mwh': 'NUMERIC(18,3)',
        'periodo': 'INTEGER',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    },
    'liq_enrrqhba': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'cantidad_mwh': 'NUMERIC(18,3)',
        'periodo': 'INTEGER',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    },
    'liq_enrrqhsu': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'cantidad_mwh': 'NUMERIC(18,3)',
        'periodo': 'INTEGER',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    },
    'liq_enrttrba': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'cantidad_mwh': 'NUMERIC(18,3)',
        'periodo': 'INTEGER',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    },
    'liq_enrttrsu': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'cantidad_mwh': 'NUMERIC(18,3)',
        'periodo': 'INTEGER',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    },
    'liq_ensecqhba': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'cantidad_mwh': 'NUMERIC(18,3)',
        'periodo': 'INTEGER',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    },
    'liq_ensecqhsu': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'cantidad_mwh': 'NUMERIC(18,3)',
        'periodo': 'INTEGER',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    },
    'liq_enterqhba': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'cantidad_mwh': 'NUMERIC(18,3)',
        'periodo': 'INTEGER',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    },
    'liq_enterqhsu': {
        'fecha': 'DATE',
        'hora': 'INTEGER',
        'qh': 'INTEGER',
        'cantidad_mwh': 'NUMERIC(18,3)',
        'periodo': 'INTEGER',
        'liquidacion': 'VARCHAR(10)',
        'source_file': 'TEXT',
    }
}
